version: '2'

services:
  postgresql:
    image: 'bitnami/postgresql:10.6.0-debian-9-r28'
    volumes:
      - 'postgresql_data:/bitnami'
  redmine:
    image: 'korlog/redmine'
    ports:
      - '80:3000'
    environment:
      - REDMINE_DB_POSTGRES=postgresql
    volumes:
      - 'redmine_data:/bitnami'
    depends_on:
      - postgresql
volumes:
  postgresql_data:
    driver: local
  redmine_data:
    driver: local